version: "3"

services:
  redis:  
    image: redis
    ports:
      - 6379:6379

  postgres:
    container_name: navegg_cdp_config_db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=navegg_cdp_config_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
      # - ./scripts/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "navegg_cdp_config_db", "-U", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10

  app:
    container_name: navegg_cdp_config_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
        redis:
          condition: service_started
        postgres:
          condition: service_healthy

volumes:
  db_data:

networks:
  backend:
    driver: bridge
