---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-database-persistent-volume-claim
  namespace: nvg-cdp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: config-postgres-cluster-ip-service
  namespace: nvg-cdp
spec:
  type: ClusterIP
  selector:
    component: config-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-postgres-deployment
  namespace: nvg-cdp
spec:
  replicas: 1
  selector:
    matchLabels:
      component: config-postgres
  template:
    metadata:
      labels:
        component: config-postgres
    spec:
      volumes:
        - name: config-postgres-storage
          persistentVolumeClaim:
            claimName: config-database-persistent-volume-claim
      containers:
        - name: config-postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: config-postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            limits:
              cpu: "650m"
              memory: "850Mi"
          env:
            - name: POSTGRES_DB
              value: config_db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-database-password
                  key: POSTGRES_PASSWORD

